### ISSUE TITLE
Invalid Url Provided

### ISSUE THREAD

**Issue by farazirfan47** [jonnnnyw/php-phantomjs#122] opened 2016-09-27 11:02 UTC
Phantomjs gives this error sometimes whats the problem,sometime it will run with the same url some time its not. here is the error

> `
> Fatal error: Uncaught exception 'JonnyW\PhantomJs\Exception\InvalidUrlException' with message 'Invalid URL provided: https://www.flipkart.com/kenstar-knc12b3p-dbh-steam-iron/p/itme9qruspved9m3?pid=IRNE9QRUFVZQKVTD&lid=LSTIRNE9QRUFVZQKVTDKECULU&fm=merchandising&iid=M_c04a7ea7-639a-435b-b2df-cd6046251478.f4f3236d-5ed9-4dc2-b3c8-4be847040da1&otracker=hp_omu_Deals of the Day_2_f4f3236d-5ed9-4dc2-b3c8-4be847040da1_f4f3236d-5ed9-4dc2-b3c8-4be847040da1_0' in C:\xampp\htdocs\monitor\vendor\jonnyw\php-phantomjs\src\JonnyW\PhantomJs\Http\AbstractRequest.php:253 Stack trace: #0 C:\xampp\htdocs\monitor\user\monitor.php(64): JonnyW\PhantomJs\Http\AbstractRequest->setUrl('https://www.fli...') #1 {main} thrown in C:\xampp\htdocs\monitor\vendor\jonnyw\php-phantomjs\src\JonnyW\PhantomJs\Http\AbstractRequest.php on line 253`

**Comment by jonnnnyw** [comment] 2016-11-15 10:31
Duplicate of https://github.com/jonnnnyw/php-phantomjs/issues/119

**Closed** 2016-11-15 10:31 UTC
Labels: duplicate
