### ISSUE TITLE
Blank Page When Trying To Run For The First Time

### ISSUE THREAD

**Issue by ScottBaxter1** [jonnnnyw/php-phantomjs#39] opened 2014-11-26 01:03 UTC
Hey guys, I'm trying to setup php-phantomjs and I've had some trouble... I'm using Laravel and i've managed to install using composer but everytime i tried to run the page I kept getting errors so I noticed someone else having the same issue on windows so I've tried what they said and this is what I've got.

Here is my config:
```php
    $client = Client::getInstance();
    $client->setBinDir('/var/www/html/hmd/vendor/bin');
    $client->setPhantomLoader('/var/www/html/hmd/vendor/jonnyw/php-phantomjs/bin');

    var_dump($client->getCommand());
```
running the above, I get this:

    string(89) "/var/www/html/hmd/vendor/bin/phantomjs /var/www/html/hmd/vendor/jonnyw/php-phantomjs/bin"

Everytime I try and run this:

```php
$client = Client::getInstance();
$client->setBinDir('/var/www/html/hmd/vendor/bin');
$client->setPhantomLoader('/var/www/html/hmd/vendor/jonnyw/php-phantomjs/bin');

$request  = $client->getMessageFactory()->createRequest();
$response = $client->getMessageFactory()->createResponse();

$request->setMethod('GET');
$request->setUrl('http://google.com');

$client->send($request, $response);

if($response->getStatus() === 200) {
    return $response->getContent();
}
```
I just get a blank page...

Any help would be great.

**Comment by jonnnnyw** [comment] 2015-02-17 14:49
Duplicate of https://github.com/jonnnnyw/php-phantomjs/issues/22

**Closed by jonnnnyw** 2015-02-17 14:49 UTC
Labels: duplicate

**Comment by critterothecreed** [comment] 2015-06-13 18:07
The reported issue here was not on windows environemnt and neither is my similar problem.

I'm also getting NULL in all fields of the Response but it only happens for me when I use custom script (am using the example code in "Writing a custom script" section from the documentation)

enabling debug in client class and printing out getLog() doesn't show any errors tho
